controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - mecanum_wheel_fr_joint
      - mecanum_wheel_rr_joint
      - mecanum_wheel_rl_joint
      - mecanum_wheel_fl_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
