controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    agrobot_controller:
      type: agrobot_controller/AgrobotController

agrobot_controller:
  ros__parameters:
    type: agrobot_controller/AgrobotController
    front_right_wheel_name: mecanum_wheel_fr_joint
    front_left_wheel_name: mecanum_wheel_fl_joint
    back_right_wheel_name: mecanum_wheel_rr_joint
    back_left_wheel_name: mecanum_wheel_rl_joint
    wheel_base: 0.715 # m
    axes_gap: 0.640 # m
    wheel_radius: 0.1 # m
    wheel_hub_radius: 0.0095 # m
    publish_rate: 20.0 # Hz
    cmd_vel_timeout: 10000.0 # ms
    velocity_rolling_window_size: 5
    base_frame_id: base_footprint
    odom_frame_id: odom
